# Generated by Django 4.0.1 on 2022-06-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
