# Generated by Django 4.0.1 on 2022-06-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25)),
                ('contact', models.TextField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.TextField(max_length=25)),
                ('cpassword', models.TextField(max_length=25)),
            ],
            options={
                'db_table': 'studentregistration',
            },
        ),
    ]
