# Generated by Django 4.0.1 on 2022-06-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
